const assert = require('node:assert/strict');
const fs = require('node:fs');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || process.argv[2] || 'playwright');
(async () => {
 const browser = await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL || 'msedge'});
 const page = await browser.newPage({viewport:{width:1440,height:960}});
 const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*', route=>{
   const url=new URL(route.request().url());
   if(url.pathname.startsWith('/static/')){
     const file='app'+url.pathname;
     if(fs.existsSync(file)) return route.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.js')?'application/javascript':'text/css'});
   }
   const file='work/multi-filter/'+url.pathname.slice(1).replaceAll('/','-')+'.html';
   if(route.request().isNavigationRequest() && fs.existsSync(file)) return route.fulfill({body:fs.readFileSync(file),contentType:'text/html'});
   return route.fulfill({body:'{}',contentType:'application/json'});
 });
 await page.goto('http://test.local/stock?grade=A&grade=B&rev=R1');
 assert.equal(await page.locator('.product-select').filter({has:page.locator('[data-multi-filter]')}).count(),0);
 const grade=page.locator('.multi-filter').filter({has:page.locator('#gradeFilter')}).locator('button');
 assert.match(await grade.innerText(), /외 1개/);
 await grade.click();
 let panel=page.locator('.multi-filter-panel:visible');
 assert.equal(await panel.locator('input:checked').count(),2);
 await panel.getByRole('button',{name:'선택 해제'}).click();
 await panel.getByRole('checkbox',{name:'A',exact:true}).check();
 await panel.getByRole('checkbox',{name:'F',exact:true}).check();
 await panel.getByRole('button',{name:'적용',exact:true}).click();
 await page.waitForURL(url=>url.searchParams.getAll('grade').includes('F'));
 let url=new URL(page.url());
 assert.deepEqual(url.searchParams.getAll('grade'),['A','F']);
 assert.equal(url.searchParams.get('rev'),'R1');
 await page.locator('input[name=keyword]').fill('한글 & 검색');
 await page.locator('input[name=keyword]').press('Enter');
 await page.waitForURL(url=>url.searchParams.get('keyword')==='한글 & 검색');
 url=new URL(page.url());assert.deepEqual(url.searchParams.getAll('grade'),['A','F']);
 await page.evaluate(()=>{const a=document.createElement('a');a.href='?page=2&grade=F';a.id='testNext';a.textContent='next';document.querySelector('.pagination').append(a);});
 await page.locator('#testNext').click();
 await page.waitForURL(url=>url.searchParams.get('page')==='2');
 assert.deepEqual(new URL(page.url()).searchParams.getAll('grade'),['A','F']);
 await grade.click();panel=page.locator('.multi-filter-panel:visible');
 await panel.getByRole('button',{name:'선택 해제'}).click();
 await panel.getByRole('button',{name:'적용',exact:true}).click();
 await page.waitForURL(url=>!url.searchParams.has('grade'));
 assert.equal(new URL(page.url()).searchParams.get('rev'),'R1');
 await page.goto('http://test.local/mrp/result?year=2025&year=2026&month=1&month=2');
 assert.deepEqual(await page.locator('#mrpYear').evaluate(s=>MultiFilter.values(s)),['2026','2025']);
 const month=page.locator('.multi-filter').filter({has:page.locator('#mrpMonth')}).locator('button');
 await month.click();panel=page.locator('.multi-filter-panel:visible');
 await panel.getByRole('checkbox',{name:'3월',exact:true}).check();
 await panel.getByRole('button',{name:'적용',exact:true}).click();
 assert.equal(await page.locator('#mrpMonth').evaluate(s=>MultiFilter.values(s).length),3);
 assert.equal(await page.locator('#mrpWeek').isDisabled(),false);
 await page.goto('http://test.local/inventory');
 const lot=page.locator('.multi-filter').filter({has:page.locator('#lotFilter')}).locator('button');
 await lot.click();panel=page.locator('.multi-filter-panel:visible');
 await panel.getByRole('checkbox',{name:'LOT,1',exact:true}).check();
 await panel.getByRole('checkbox',{name:'LOT&2',exact:true}).check();
 await panel.getByRole('button',{name:'적용',exact:true}).click();
 await page.waitForURL(url=>url.searchParams.getAll('lot').length===2);
 assert.deepEqual(new Set(new URL(page.url()).searchParams.getAll('lot')),new Set(['LOT,1','LOT&2']));
 await lot.click();
 await page.screenshot({path:'work/multi-filter/desktop.png'});
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('.multi-filter-panel:visible').count(),0);
 await page.setViewportSize({width:390,height:844});
 await lot.click();panel=page.locator('.multi-filter-panel:visible');
 const box=await panel.boundingBox();assert.ok(box.x>=0 && box.x+box.width<=390);
 await page.screenshot({path:'work/multi-filter/mobile.png'});
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Browser checks passed: multi-select, reset, query persistence, special values, MRP dependencies, keyboard and mobile.');
})().catch(error=>{console.error(error);process.exit(1)});
